version: '3.7'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - '3306:3306'
    volumes:
      - ./.data:/var/lib/mysql
      - ./src/test/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql